/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package heesun;

import java.sql.Connection;
import java.sql.SQLException;

import heesun.config.DBconfig;
import heesun.model.StudentRepository;
import heesun.service.StudentService;

public class DBApp {

    public static void main(String[] args) throws SQLException {
        Connection conn = DBconfig.getConnection();
        StudentRepository studentRepository = new StudentRepository(conn);
        StudentService studentService = new StudentService(studentRepository, conn);

        // studentService.insertStudent("희선", 26, "01022999793",
        // "heesun9793@naver.com");
        // studentService.insertStudent("영희", 20, "01011112222", "hee@naver.com");
        // studentService.deleteById(1);
        // studentService.update(2, "영희", 20, "01022223333", "hee@naver.com");
        // studentService.insert("철수", 20, "01099990000", "soo@nate.com");

        studentService.insert("희선", 30, "01022223333", "hee@naver.com");
    }

}